[project]
name = "hypercat"
version = "0.1.0"
description = "A Python framework for higher category theory, homotopy, and hyperstructural data modeling"
readme = "README.md"
requires-python = ">=3.9"
license = {text = "MIT"}
authors = [
  { name = "Marco Cividini", email = "your.email@example.com" }
]
keywords = ["category theory", "homotopy", "diagrams", "topos", "commutativity", "higher categories"]

classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Intended Audience :: Science/Research",
  "Topic :: Scientific/Engineering :: Mathematics"
]

dependencies = [
  "networkx >= 2.6",
  "matplotlib >= 3.5",
  "pydot >= 1.4",
  "graphviz >= 0.20",
  "sympy >= 1.10"
]

[project.optional-dependencies]
dev = [
  "pytest >= 7.0",
  "black",
  "flake8",
  "mypy"
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"
