name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install pytest nbclient
    
    - name: Import smoke test
      run: |
        python -c "
        import hypercat
        from hypercat.core import Category, Object, Morphism
        print('hypercat ok:', getattr(hypercat, '__version__', 'unknown'))
        "
    
    - name: Run tests
      run: |
        pytest -v
    
    - name: Test core imports
      run: |
        python -c "
        from hypercat import Category, Object, Morphism, Functor, NaturalTransformation
        from hypercat.categories import StandardCategories
        from hypercat.higher import TwoCategory
        print('All key classes accessible')
        "
    
    - name: Test notebooks execute
      run: |
        jupyter nbconvert --execute --to notebook examples/00_quickstart.ipynb --output /tmp/quickstart_test.ipynb
        # Test other notebooks if they don't require external data
        # jupyter nbconvert --execute --to notebook examples/HyperCatDemo.ipynb --output /tmp/demo_test.ipynb

  # Optional job for PyPy (allow failure)
  test-pypy:
    runs-on: ubuntu-latest
    continue-on-error: true
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up PyPy
      uses: actions/setup-python@v4
      with:
        python-version: 'pypy-3.10'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install pytest
    
    - name: Import smoke test
      run: |
        python -c "
        import hypercat
        print('hypercat ok on PyPy:', getattr(hypercat, '__version__', 'unknown'))
        "
    
    - name: Run basic tests
      run: |
        pytest src/tests/testcat.py -v